# Generated by Django 4.0 on 2021-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
