# Generated by Django 4.0 on 2021-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('person', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
