# Generated by Django 3.1.7 on 2021-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
