# Generated by Django 3.1.7 on 2021-03-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20210309_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('long', models.URLField(max_length=500, unique=True)),
                ('short', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
